### PR TITLE
Export as PNG

### LINKED ISSUE #3: Render to image

### PR DESCRIPTION
**Pull request by damonsk**
Fixes #3 - using html2canvas to generate image client side.

### CODE REVIEW

**Comment by cdaniel** [comment]
Thank you @damonsk . This is merged and running now!

**Comment by cdaniel** [comment]
@damonsk , a question though - generated pngs do not have the link to the forum included - how did you achieve that?

**Comment by damonsk** [comment]
Hi Chris, PNGs are just images. For them to be clickable they’ll likely need to be HTML or maybe PDFs.

**Comment by cdaniel** [comment]
@damonsk  I get that :D. 
See what is missing from the PNG. I like that, but I wonder how did you do that, since there is no filter in your patch visible.
Doctrine (4)

**Comment by damonsk** [comment]
Ahh I understand now.  I notice you're using FontAwesome.  I replaced the icon with a span and just text and it rendered in the output.  There are various issues open in html2canvas in relation to font awesome.

I've had similar issues with OWM and google fonts.

Happy to do some more digging around if you like?

**Comment by cdaniel** [comment]
@damonsk no need to dig further, thank you!

I thought there is some magic going on and you have hidden those discussion links (which make no sense in a png file) on purpose, I really wanted to learn how to do that.

But if this is the bug/feature of html2canvas that works/fails only with FontAwesome, then this is enough for me :).

**Pull request merged**
